const { setHandlebarHelpers } = require('./utility');
const { generateCSS_AspectRatio } = require('./layout/aspect-ratio');
const { generateCSS_ColumnWidth } = require('./layout/column-width');
const { generateCSS_ColumnGap } = require('./layout/column-gap');
const { generateCSS_ColumnCount } = require('./layout/column-count');
const { generateCSS_BreakAfter } = require('./layout/break-after');
const { generateCSS_BreakBefore } = require('./layout/break-before');
const { generateCSS_BreakInside } = require('./layout/break-inside');
const { generateCSS_BoxDecorationBreak } = require('./layout/box-decoration-break');
const { generateCSS_BoxSizing } = require('./layout/box-sizing');
const { generateCSS_Display } = require('./layout/display');
const { generateCSS_Float } = require('./layout/float');
const { generateCSS_Clear } = require('./layout/clear');
const { generateCSS_Isolation } = require('./layout/isolation');
const { generateCSS_ObjectFit } = require('./layout/object-fit');
const { generateCSS_ObjectPosition } = require('./layout/object-position');
const { generateCSS_Overflow } = require('./layout/overflow');
const { generateCSS_OverscrollBehavior } = require('./layout/overscroll-behavior');
const { generateCSS_Position } = require('./layout/position');
const { generateCSS_Visibility } = require('./layout/visibility');
const { generateCSS_ZIndex } = require('./layout/z-index');
const { generateCSS_TopRightBottomLeft } = require('./layout/top-right-bottom-left');

setHandlebarHelpers();

generateCSS_AspectRatio();
generateCSS_ColumnWidth();
generateCSS_ColumnGap();
generateCSS_ColumnCount();
generateCSS_BreakAfter();
generateCSS_BreakBefore();
generateCSS_BreakInside();
generateCSS_BoxDecorationBreak();
generateCSS_BoxSizing();
generateCSS_Display();
generateCSS_Float();
generateCSS_Clear();
generateCSS_Isolation();
generateCSS_ObjectFit();
generateCSS_ObjectPosition();
generateCSS_Overflow();
generateCSS_OverscrollBehavior();
generateCSS_TopRightBottomLeft();
generateCSS_Position();
generateCSS_Visibility();
generateCSS_ZIndex();
